### ISSUE TITLE
Criar diagrama de relacionamento entre classe

### ISSUE THREAD

**Issue by ANadrowski** [codenation-dev/squad-1-ad-java-e-vue-online-ca#1]
Como todas as tabelas do DB serão criadas pelo Hibernate, seria interessante criarmos um diagrama de classes demonstrando o relacionamento entre estas tabelas.

**Comment by ajunior** [comment]
Os diagramas de classes e das tabelas já estão no repositório, na pasta [assets](https://github.com/codenation-dev/squad-1-ad-java-e-vue-online-ca-back/tree/master/assets).
